FROM maven:3.9.8-amazoncorretto-21-al2023 AS build

RUN mkdir /measurement-schema
COPY measurement-schema /measurement-schema/.
RUN cd /measurement-schema && mvn clean install

RUN mkdir /warehouse-service
COPY warehouse-service /warehouse-service/.
#skip integration tests because it needs dind (Docker in Docker) image
RUN cd /warehouse-service && mvn clean install -DskipITs -T 2C

FROM amazoncorretto:21
COPY --from=build /warehouse-service/target/*.jar /app.jar

ENTRYPOINT ["java", \
  "-Dspring.profiles.active=local", \
  "-jar", "/app.jar" \
  ]