spring:
  config:
    activate:
      on-profile: local
  application:
    name: 'warehouse-service'
  kafka:
    admin:
      fail-fast: true
    bootstrap-servers: localhost:19092
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer"
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
      acks: "all"

app:
  warehouse-id: 'default'
  temperature:
    server-port: 3344
  humidity:
    server-port: 3345